# permissions for end users to edit workflowruntimes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: workflowruntime-editor-role
rules:
- apiGroups:
  - serverless.tass.io
  resources:
  - workflowruntimes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - serverless.tass.io
  resources:
  - workflowruntimes/status
  verbs:
  - get
