# This file defines the Kubernetes objects necessary for Tass to run within Kubernetes.
# Apply this file before using the operator.
#
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tass-operator
  labels:
    app: tass-operator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["serverless.tass.io"]
  resources: ["workflowruntimes"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]