apiVersion: serverless.tass.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-sample
spec:
  env:
    lang: CH
    kind: cron
  spec:
  - name: entrance
    function: function1
    outputs:
    - next
    statement: direct
    role: start
  - name: next
    function: function2
    statement: switch
    conditions:
    - name: root
      type: int
      operator: eq
      target: $
      comparision: 5
      destination:
        isTrue:
          flows:
          - left
        isFalse:
          flows:
          - right
  - name: left
    function: function3
    outputs:
    - end
    statement: direct
  - name: end
    function: function4
    statement: direct
    role: end
  - name: right
    function: function1
    statement: direct
    role: end
    