apiVersion: serverless.tass.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-sample
spec:
  # Add fields here
  environment: Golang
  spec:
  - name: flow-sample
    function: hello
    inputs:
    - hi
    - hey
    outputs:
    - exit
    - bye
    statement: loop
    condition:
      type: string
      operator: eq
      target: goodbye
