apiVersion: serverless.tass.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-sample
spec:
  # Add fields here
  environment: Golang
  domain: sail
  spec:
  - name: flow-sample
    function: function-sample
    inputs:
    - hi
    - hey
    outputs:
    - exit
    - bye
    statement: switch
    condition:
      type: string
      operator: eq
      comparision: money
      destination:
        isTrue: [exit]
        isFalse: [bye]
