apiVersion: serverless.tass.io/v1alpha1
kind: Workflow
metadata:
  name: workflow-sample
spec:
  environment: Golang
  spec:
  - name: entrance
    function: function1
    outputs:
    - next
    statement: direct
  - name: next
    function: function2
    inputs:
    - entrance
    outputs:
    - left
    - right
    statement: switch
    condition:
      type: int
      operator: eq
      comparision: 5
      destination:
        isTrue:
        - left
        isFalse:
        - right
  - name: left
    function: function3
    inputs:
    - next
    outputs:
    - end
    statement: direct
  - name: end
    function: function4
    statement: direct
    inputs:
    - left
  - name: right
    function: function1
    statement: direct
    inputs:
    - next
    